### PR TITLE
Dockerfile + Docker-compose update for DevStack

### PR DESCRIPTION
**Pull request by xakraz**
Suggest a Dockerfile and docker-compose update to run seedbox as a "stack" in dev

By the way, it is missing the DB Schema initialization ...

### CODE REVIEW

**Comment by xakraz** [comment]
@nailgun : Can you provide the DB schema management so that we can have a usable seedbox ?

Thx :)

**Comment by nailgun** [comment]
@xakraz Thanks for the PR! It looks good. Glad someone interested on the project.

I have some questions:
* Why did you change Dockerfile version?
* Is it possible to move migrations package to seedbox package? (I'm actually from Django-world, don't have large experience with flask)

**Comment by xakraz** [comment]
I have changed the version od `docker-compose` api because the v3 does not support the Gateway statement in the network section yet ... And I have to admit that I did not dig into the issue yet :D

**Comment by xakraz** [comment]
For the migration package, yes no problem.
I have put it there but I have absolutely no experience in dev best practices....

**Pull request merged**
